[package]
name = "open_combat"
version = "0.1.0"
authors = ["Sevajol Bastien <contact@bux.fr>"]
edition = "2018"

[dependencies]
ggez = { git = "https://github.com/ggez/ggez", tag = "0.6.0-rc0" }
glam = "0.12.0"
tiled = "0.9.5"
pathfinding = "2.1.4"
bresenham = "0.1.1"
