core:
    cycle_duration: 0.25
    use_x_cores: 2
terminals:
    sync: True
game:
    look_around:
        frequency: 1
    engage:
        frequency: 1
    move:
        walk_ref_time: 3
        run_ref_time: 1
        crawl_ref_time: 10
        rotate_ref_time: 0  # seconds per degrees
        subject:
          tank1:
            global_move_coeff: 3
            rotate_ref_time: 0.1111  # seconds per degrees
    building:
      draw_interior_gap: 2

global:
    cache_dir_path: 'cache'
    include_path:
      maps:
        - "maps"
      graphics:
        - "medias/images"
      sounds:
        - "medias/sounds"
    logging_level: ERROR
    debug: false
    debug_gui: false
